version: '3'
services:
  algamoney-db:
    build: ../algamoney-db
    environment:
      - "POSTGRES_PASSWORD=TR!c0lor"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "su", "postgres", "-c", "psql -h localhost -p 5432 -q"]
      interval: 30s
      timeout: 10s
      retries: 5
  algamoney-api:
    build: ../algamoney-api-server
    ports:
      - "8080:8080"
      - "8081:8081"
    restart: on-failure
    depends_on:
    - "algamoney-db"
  algamoney-ui:
    build: ../algamoney-ui-server
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
    - "algamoney-api"
  mongo:
    image: mongo:3
    ports:
      - "27017:27017"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "http.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  graylog:
    image: graylog/graylog:3.1
    links:
      - "mongo"
      - "elasticsearch"
    ports:
      - "9000:9000"
      - "1514:1514"
      - "1514:1514/udp"
      - "12201:12201"
      - "12201:12201/udp"
    environment:
      - "GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/"
    restart: on-failure
    depends_on:
    - "mongo"
    - "elasticsearch"