version: '3'
services:
  algamoney-db:
    build: ../algamoney-db
    environment:
      - "POSTGRES_PASSWORD=TR!c0lor"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "su", "postgres", "-c", "psql -h localhost -p 5432 -q"]
      interval: 30s
      timeout: 10s
      retries: 5
  algamoney-api:
    build: ../algamoney-api-server
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
    - "algamoney-db"