version: '3.7'
services:
  mongo:
    build: ../../algamoney-mongodb
    ports:
      - "27017:27017"
    networks:
      - backend-infra
  elasticsearch:
    build: ../../algamoney-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "http.host=0.0.0.0"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - backend-infra
  graylog:
    build: ../../algamoney-graylog 
    ports:
      - "9000:9000"
      - "1514:1514"
      - "1514:1514/udp"
      - "12201:12201"
      - "12201:12201/udp"
    environment:
      - "GRAYLOG_HTTP_EXTERNAL_URI=${GRAYLOG_EXTERNAL_URL}"
    restart: on-failure
    networks:
      - backend-infra
      - backend-api
    depends_on:
    - "mongo"
    - "elasticsearch"
  grafana:
    build: ../../algamoney-grafana
    ports:
      - "3000:3000"
    networks:
      - backend-infra
    healthcheck:
      test: ["CMD", "curl", "--fail", "${GRAFANA_URL}"]
      interval: 90s
      timeout: 10s
      retries: 5

networks:
  backend-infra:
    driver: bridge
  backend-api:
    driver: bridge